name: Push-SpringBootCode-to-EC2 instance from dev branch
 
# Trigger deployment only on push to dev branch
on:
  workflow_dispatch:  
  push:
    branches: 
      - dev

jobs: 
  deploy:
    name: Push to EC2 on dev branch push
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          ref: dev
      - name: Debug Secrets
        run: |
          echo "HOST_DNS: ${{ secrets.HOST_DNS }}"
          echo "EC2_USER: ${{ secrets.EC2_USER }}"
          echo "TARGET_DIR: ${{ secrets.TARGET_DIR }}"
 
      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./backend"
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: "devuser"
          TARGET: "/home/devuser/"
          ARGS: "--rsync-path='sudo rsync'"

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST_DNS }} 
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "${{ secrets.USER_PASSWORD }}" | sudo -S apt update
            cd /home
            ls
            cd devuser
            cd backend
            sudo mvn clean package
            sudo cp -r target/*  /var/www/html/target/
            cd  /var/www/html/target/
            nohup java -jar springboot-backend-0.0.1-SNAPSHOT.jar > app.log 2>&1 &

            ps aux | grep springboot-backend
