name: Push-Recactcode-to-EC2 instance from dev branch

# Trigger deployment only on push to dev branch
on:
  workflow_dispatch:
  push:
    branches:  
      - dev   
 
jobs:    
  deploy:  
    name: Push to EC2 on dev branch push 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          ref: dev
      - name: Debug Secrets
        run: |
          echo "HOST_DNS: ${{ secrets.HOST_DNS }}" 
          echo "EC2_USER: ${{ secrets.EC2_USER }}"
          echo "TARGET_DIR: ${{ secrets.TARGET_DIR }}"

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./frontend"
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: "devuser"
          TARGET: "/home/devuser/"

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "${{ secrets.USER_PASSWORD }}" | sudo -S apt update
            cd /home
            ls
            cd serviceuser
            cd frontend 
            sudo apt install npm 
            sudo npm install react-router-dom
            echo "${{ secrets.USER_PASSWORD }}" | sudo -S npm run build
            echo "${{ secrets.USER_PASSWORD }}" | sudo -S cp -r build/* /var/www/html/
            echo "${{ secrets.USER_PASSWORD }}" | sudo -S systemctl restart apache2
      - name: Copy MySQL Dump to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./dump/reactservicedeskdatabase_script_1.sql"
          target: "/home/devuser/"
          script:
            mysql -u root -p ${{ secrets.MYSQL_PASSWORD }} reactservicedeskdatabase </home/serviceuser/dump/reactservicedeskdatabase_script_1.sql
            sudo systemctl restart mysql
